#!/usr/bin/python3
# ./do build
# docker build -t invariant-docs .
# ./do serve
# docker build -t invariant-docs . && docker run -it -p 8000:8000 -e DEV_MODE=true -v .:/docs/ invariant-docs

import sys
import time
import subprocess
import webbrowser

if sys.argv[1] == 'build':
    print('Building image...')
    subprocess.run(['docker', 'build', '-t', 'invariant-docs', '.'])
elif sys.argv[1] == 'serve':
    print('Building image...')
    p = subprocess.Popen(['docker', 'build', '-t', 'invariant-docs', '.'], stdout=subprocess.PIPE)
    p.wait()
    print('Starting server...')
    p = subprocess.Popen("docker run -it -p 8000:8000 -e DEV_MODE=true -v .:/docs/ invariant-docs", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    time.sleep(1)
    webbrowser.open('http://localhost:8000')
    p.wait()
else:
    print('Usage: ./do build | ./do serve')
    sys.exit(1)