#!/usr/bin/python3
# ./run build
# docker build -t invariant-docs .
# ./run serve
# docker build -t invariant-docs . && docker run -it -p 8000:8000 -e DEV_MODE=true -v .:/docs/ invariant-docs

import sys
import time
import subprocess
import webbrowser

# Check the correct number of arguments
if len(sys.argv) != 2:
    print("Usage: ./run <build|up>")
    sys.exit(1)

# Build the image
if sys.argv[1] == "build":
    print("Building image...")
    subprocess.run(["docker", "build", "-t", "invariant-docs", "."])
elif sys.argv[1] == "up":
    print("Building image...")
    p = subprocess.Popen(
        ["docker", "build", "-t", "invariant-docs", "."], stdout=subprocess.PIPE
    )
    p.wait()
    print("Starting server...")
    p = subprocess.Popen(
        "docker run -it -p 8000:8000 -e DEV_MODE=true -v .:/docs/ invariant-docs",
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    time.sleep(1)
    webbrowser.open("http://localhost:8000")
    p.wait()
else:
    print("Usage: ./run <build|up>")
    sys.exit(1)
